# Generated by Django 4.0.4 on 2022-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default=62123456789, max_length=20),
            preserve_default=False,
        ),
    ]
